#!/usr/bin/env python3
# Copyright © 2025 Constantinos Vidiniotis. All rights reserved.
# Licensed under Elastic License 2.0 — see LICENSE.md for details.
"""CRP v6 Agent SDK — security report reference agent.

Demonstrates a multi-step agent that scans a target, interprets raw findings,
and renders a final report.  The mock scanner is deterministic; in production
this agent would connect to CRP Scan, a real vulnerability feed, or a SIEM.
"""

from __future__ import annotations

import json
import re
from typing import Any

import crp
from crp.providers.custom import CustomProvider

# ── Mock scanner backend ────────────────────────────────────────────────────

_FINDINGS: dict[str, list[dict[str, Any]]] = {
    "https://api.example.com": [
        {"id": "CRP-001", "severity": "HIGH", "title": "Missing CRP governance headers"},
        {"id": "CRP-003", "severity": "MEDIUM", "title": "Tool calls not constrained by grammar"},
    ],
    "https://app.example.com": [
        {"id": "CRP-002", "severity": "HIGH", "title": "Unverified provider key storage"},
    ],
}


# ── Tools ───────────────────────────────────────────────────────────────────

def scan_target(url: str) -> dict[str, Any]:
    """Run a governance scan against ``url`` and return findings."""
    findings = _FINDINGS.get(url, [])
    return {
        "target": url,
        "findings": findings,
        "summary": f"{len(findings)} finding(s) detected.",
    }


def summarize_findings(findings_json: str) -> dict[str, Any]:
    """Summarize a list of findings by severity."""
    try:
        findings = json.loads(findings_json)
    except json.JSONDecodeError:
        return {"error": "invalid JSON"}
    by_severity: dict[str, int] = {}
    for f in findings:
        by_severity[f.get("severity", "UNKNOWN")] = by_severity.get(f.get("severity", "UNKNOWN"), 0) + 1
    return {"total": len(findings), "by_severity": by_severity}


def generate_report(title: str, format: str = "markdown") -> dict[str, Any]:
    """Generate a report document with the given title and format."""
    valid_formats = {"markdown", "json", "pdf"}
    fmt = format.lower() if format.lower() in valid_formats else "markdown"
    return {
        "title": title,
        "format": fmt,
        "document": f"# {title}\n\nGenerated by CRP governed report agent.",
    }


# ── Mock SLM provider ───────────────────────────────────────────────────────


def _mock_generate(messages: list[dict[str, str]]) -> tuple[str, str]:
    prompt = messages[-1]["content"]
    lower = prompt.lower()
    objective_match = re.search(r"objective:\s*(.+)", prompt, re.IGNORECASE)
    objective = (objective_match.group(1).strip() if objective_match else lower).lower()

    url_match = re.search(r"https?://[\w.-]+(?:/[\w.-]*)?", objective)
    url = url_match.group(0) if url_match else "https://api.example.com"

    if "scan" in objective or "check" in objective or "audit" in objective:
        return (
            json.dumps({
                "capability_id": "scan_target",
                "arguments": {"url": url},
            }),
            "stop",
        )

    if "summarize" in objective or "interpret" in objective or "severity" in objective:
        findings = _FINDINGS.get("https://api.example.com", [])
        return (
            json.dumps({
                "capability_id": "summarize_findings",
                "arguments": {"findings_json": json.dumps(findings)},
            }),
            "stop",
        )

    if "report" in objective or "generate" in objective or "document" in objective:
        return (
            json.dumps({
                "capability_id": "generate_report",
                "arguments": {"title": "CRP Governance Scan Report", "format": "markdown"},
            }),
            "stop",
        )

    return (
        json.dumps({
            "capability_id": None,
            "answer": "I can scan a target, summarize findings, and generate a report.",
        }),
        "stop",
    )


provider = CustomProvider(
    generate_fn=_mock_generate,
    count_tokens_fn=lambda text: max(1, len(text.split())),
    context_size=8192,
    name="mock-slm",
)


# ── Agent declaration ───────────────────────────────────────────────────────

agent = crp.Agent(
    provider=provider,
    tools=[scan_target, summarize_findings, generate_report],
    system=(
        "You are a security-reporting assistant. Scan targets, summarize "
        "findings, and produce structured reports. Always cite the target URL."
    ),
    profile="capable-local",
)


# ── Run ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # Step 1: scan.
    scan_result = agent.run("Scan https://api.example.com")
    print("Scan:", scan_result.answer[:200])
    print("Operations:", scan_result.how_it_was_built)

    # Step 2: summarize the findings.
    summary_result = agent.run(
        "Summarize the findings",
        prior_cso=scan_result.cso,
    )
    print("Summary:", summary_result.answer)
    print("Operations:", summary_result.how_it_was_built)

    # Step 3: generate the final report.
    report_result = agent.run(
        "Generate a markdown report",
        prior_cso=summary_result.cso,
    )
    print("Report:", report_result.answer[:200])
    print("Operations:", report_result.how_it_was_built)
